theme: jekyll-theme-modernist
title: Bayesian modelling using the brms package
subtitle: From research question to final report, unleashing the full potential of brms
date: 2021-12-06
author: Louise Litrico
